trigger:
  - main
pool:
      vmImage: 'ubuntu-latest'
variables:
  imageName: 'jyothika1234/fastapi-img'
  tag: '$(Build.BuildId)'
  containerRegistry: 'dockerHubLink'
  

stages:
- stage: Build
  jobs:
  - job: 
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
        displayName: 'Use Python 3.11'
        addToPath: true
    - script: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - task: ArchiveFiles@2
      displayName: 'Archive Files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(imageName)-$(tag).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Build Artifacts'

- stage: DockerBuild
  jobs:
  - job: 
    steps:
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Deploy
  jobs:
      - job: 
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'test-service-connection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az aks get-credentials --resource-group test-rg1 --name cluster-03
              kubectl apply -f deployment.yaml           